"""
Create import aliases so Windows wheel package names match upstream Pixal3D imports.

Pixal3D expects:  flex_gemm, cumesh, o_voxel
Windows wheels:   flex_gemm_ap, cumesh_vb  (o_voxel has a full wheel — prefer that)
"""
from __future__ import annotations

import importlib
import site
import sys
from pathlib import Path


ALIASES = {
    "flex_gemm": ("flex_gemm_ap",),
    "cumesh": ("cumesh_vb",),
    "o_voxel": ("o_voxel_vb_ap", "o_voxel_vb"),
}

MARKER = "alias_cuda_packages"

SITECUSTOMIZE = r'''
# Auto-generated by scripts/alias_cuda_packages.py
from __future__ import annotations

import importlib
import importlib.abc
import importlib.util
import sys

_ALIAS_ROOTS = {
    "flex_gemm": "flex_gemm_ap",
    "cumesh": "cumesh_vb",
    "o_voxel": "o_voxel_vb_ap",
}


def _resolve_root(alias: str):
    real = _ALIAS_ROOTS.get(alias)
    if real is None:
        return None
    if importlib.util.find_spec(real) is not None:
        return real
    if alias == "o_voxel" and importlib.util.find_spec("o_voxel_vb") is not None:
        return "o_voxel_vb"
    return None


class _AliasFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path, target=None):  # noqa: ARG002
        for alias in list(_ALIAS_ROOTS):
            if fullname == alias or fullname.startswith(alias + "."):
                for finder in sys.meta_path:
                    if finder is self or isinstance(finder, _AliasFinder):
                        continue
                    try:
                        spec = (
                            finder.find_spec(fullname, path, target)
                            if hasattr(finder, "find_spec")
                            else None
                        )
                    except Exception:
                        spec = None
                    if spec is not None and fullname == alias:
                        return None

                real_root = _resolve_root(alias)
                if real_root is None:
                    return None
                real_name = real_root + fullname[len(alias) :]
                try:
                    real_mod = importlib.import_module(real_name)
                except ImportError:
                    return None
                sys.modules[fullname] = real_mod
                return importlib.util.find_spec(real_name)
        return None


if not any(isinstance(f, _AliasFinder) for f in sys.meta_path):
    if (
        importlib.util.find_spec("o_voxel_vb_ap") is None
        and importlib.util.find_spec("o_voxel_vb") is not None
    ):
        _ALIAS_ROOTS["o_voxel"] = "o_voxel_vb"
    # Do not alias o_voxel when the real package is installed
    if importlib.util.find_spec("o_voxel") is not None:
        # Only keep aliases for missing canonical names via shim files;
        # finder still helps submodule resolution for flex_gemm/cumesh.
        pass
    sys.meta_path.insert(0, _AliasFinder())
'''


def _site_packages() -> Path:
    paths = [Path(p) for p in site.getsitepackages()]
    for p in paths:
        if p.exists() and "site-packages" in str(p):
            return p
    if site.getusersitepackages():
        return Path(site.getusersitepackages())
    return paths[0]


def _can_import(name: str) -> bool:
    try:
        importlib.import_module(name)
        return True
    except Exception:
        return False


def main() -> int:
    dest = _site_packages()
    print(f"Site-packages: {dest}")

    sc = dest / "sitecustomize.py"
    if sc.exists() and MARKER not in sc.read_text(encoding="utf-8", errors="ignore"):
        hook = dest / "_pixal3d_win_aliases.py"
        hook.write_text(SITECUSTOMIZE, encoding="utf-8")
        (dest / "pixal3d_aliases.pth").write_text("import _pixal3d_win_aliases\n", encoding="utf-8")
        print(f"  wrote {hook} and pixal3d_aliases.pth")
    else:
        sc.write_text(SITECUSTOMIZE, encoding="utf-8")
        print(f"  wrote {sc}")

    ok = True
    for canonical, alts in ALIASES.items():
        if _can_import(canonical):
            print(f"[OK] {canonical} already importable")
            continue
        actual = next((a for a in alts if _can_import(a)), None)
        if actual is None:
            print(f"[MISSING] {canonical} (need one of {alts})")
            ok = False
            continue

        actual_dir = dest / actual
        if actual_dir.is_dir():
            pkg = dest / canonical
            pkg.mkdir(exist_ok=True)
            (pkg / "__init__.py").write_text(
                f"# Auto-generated alias ({MARKER}): {canonical} -> {actual}\n"
                f"import sys\n"
                f"import {actual} as _real\n"
                f"sys.modules[__name__] = _real\n",
                encoding="utf-8",
            )
            print(f"[ALIAS] package {canonical}/ -> {actual}/")
        else:
            (dest / f"{canonical}.py").write_text(
                f"# Auto-generated alias ({MARKER}): {canonical} -> {actual}\n"
                f"import sys\n"
                f"import {actual} as _real\n"
                f"sys.modules[__name__] = _real\n",
                encoding="utf-8",
            )
            print(f"[ALIAS] module {canonical}.py -> {actual}")

        for key in list(sys.modules):
            if key == canonical or key.startswith(canonical + "."):
                del sys.modules[key]
        if _can_import(canonical):
            print(f"  verified import {canonical}")
        else:
            print(f"  WARNING: still cannot import {canonical}")
            ok = False

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
